### ISSUE TITLE
Endpoints for optional date parameters

### ISSUE THREAD

**Issue by malikwas** [kshvmdn/nba-scores#17]
Hey all,

Currently in [DATA.md](https://github.com/kshvmdn/nba.js/blob/master/docs/api/DATA.md), there are a list of endpoints with `current` set as the date in the URL. For example:

  - `divisionStandings`
    + Endpoint: [`/data/10s/prod/v1/current/standings_division.json`](http://data.nba.net/data/10s/prod/v1/current/standings_division.json)

So, I wanted to see if I could get division standings for any random date during the season, such as March 3, 2017. [Turns out it actually does return a response for that exact date.
](http://data.nba.net/data/10s/prod/v1/20170303/standings_division.json)
Should the endpoints and docs be edited in the library to show this? I think this works for all `current` instances in the URL, where we can replace it with `YYYYMMDD`. What's the best way to make this change, then?

**Comment by kashav** [comment]
@malikwas nice find, thanks for the issue! This _will_ require a doc change, feel free to submit a PR.

I'm thinking we replace all mentions of `current` with `{{date}}` (just like the `scoreboard` method). We should also include `current` as an option in the parameter reference for `date` (with a note mentioning that it doesn't work for `scoreboard`).

I'm open to other ideas, so let me know if you have another suggestion!

**Comment by kashav** [comment]
Closed by #18.
